spring:
  profiles:
    active: prod
  application:
    name: address-book
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    com.capgemini.payroll_app.service: DEBUG
    com.capgemini.payroll_app.controller: WARN
    com.capgemini.payroll_app.entity : WARN
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %level - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"